// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiDImFThqNczlwuj3zD3Yl1BNHkMi4b64',
    appId: '1:1070953394604:web:4213058b4c56cde81d0a09',
    messagingSenderId: '1070953394604',
    projectId: 'event-manager-flutter-app',
    authDomain: 'event-manager-flutter-app.firebaseapp.com',
    storageBucket: 'event-manager-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpJNDA8swSHo_zjRpQ5Cx6NM4Lqtuseb0',
    appId: '1:1070953394604:android:d5e0b908f0c164861d0a09',
    messagingSenderId: '1070953394604',
    projectId: 'event-manager-flutter-app',
    storageBucket: 'event-manager-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3wqIKt_xP8ziF_34ntSqaYM1B_Ulx5Vc',
    appId: '1:1070953394604:ios:ea837cabfb125b061d0a09',
    messagingSenderId: '1070953394604',
    projectId: 'event-manager-flutter-app',
    storageBucket: 'event-manager-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.eventManagerFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3wqIKt_xP8ziF_34ntSqaYM1B_Ulx5Vc',
    appId: '1:1070953394604:ios:ea837cabfb125b061d0a09',
    messagingSenderId: '1070953394604',
    projectId: 'event-manager-flutter-app',
    storageBucket: 'event-manager-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.eventManagerFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiDImFThqNczlwuj3zD3Yl1BNHkMi4b64',
    appId: '1:1070953394604:web:e066965430ff94901d0a09',
    messagingSenderId: '1070953394604',
    projectId: 'event-manager-flutter-app',
    authDomain: 'event-manager-flutter-app.firebaseapp.com',
    storageBucket: 'event-manager-flutter-app.firebasestorage.app',
  );
}
